GM_setValue('percentThreshold_BTCUSD', 70)
  GM_setValue('percentThreshold_ETHUSD', 70)
  GM_setValue('percentThreshold_XRPUSD', 80)
  GM_setValue('percentThreshold_ETCUSD', 70)
  GM_setValue('percentThreshold_ZECUSD', 70)
  GM_setValue('percentThreshold_DASHUSD', 70)

GM_setValue('dynLevelCoef_BTCUSD', 1.82)
  GM_setValue('dynLevelCoef_ETHUSD', 1.79)
  GM_setValue('dynLevelCoef_XRPUSD', 1.79)
  GM_setValue('dynLevelCoef_ETCUSD', 1.78)
  GM_setValue('dynLevelCoef_ZECUSD', 1.96)
  GM_setValue('dynLevelCoef_DASHUSD', 2.11)

  GM_setValue('dynLevelSafe_BTCUSD', 50)
  GM_setValue('dynLevelSafe_ETHUSD', 50)
  GM_setValue('dynLevelSafe_XRPUSD', 50)
  GM_setValue('dynLevelSafe_ETCUSD', 70)
  GM_setValue('dynLevelSafe_ZECUSD', 70)
  GM_setValue('dynLevelSafe_DASHUSD', 70)

  GM_setValue('diffThreshold_BTCUSD', [-5, 9])
  GM_setValue('diffThreshold_ETHUSD', [-0.26, 0.2])
  GM_setValue('diffThreshold_XRPUSD', [-0.00028, 0.00028])
  GM_setValue('diffThreshold_ETCUSD', [-0.2, -0.2])
  GM_setValue('diffThreshold_ZECUSD', [-0.04, 0.14])
  GM_setValue('diffThreshold_DASHUSD', [-0.16, 0.24])

  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])

GM_setValue('maxBalance', 290)
GM_setValue('minBalance', 3)
GM_setValue('stopLossPercent', 10)
GM_setValue('maxOpenTrades', 1)
 GM_setValue('minDelayBetweenOrdersSec', 65)
GM_setValue('orderUpdate', true)
GM_setValue('reloadOnConnectionReset', true)
GM_setValue('orderUpdateRandomFlag', false)
GM_setValue('orderPercent', 0)
GM_setValue('orderPercentMin', 5)
GM_setValue('orderPercentMax', 5)
GM_setValue('minDelayBetweenOrdersSecDelay', [7200, 10800 ])
GM_setValue('delayLevelToMinOrder', 1.6)
GM_setValue('delayLevelToStop', 2.6)
GM_setValue('orderMax', 5)
GM_setValue('orderMin', 1)
GM_setValue('orderRoundCoef', 1)
GM_setValue('soundON', false)
