

  GM_setValue('percentThreshold_BTCUSD', 80)
  GM_setValue('percentThreshold_ETHUSD', 80)
  GM_setValue('percentThreshold_XRPUSD', 75)
  GM_setValue('percentThreshold_ETCUSD', 75)
  GM_setValue('percentThreshold_ZECUSD', 80)
  GM_setValue('percentThreshold_DASHUSD', 70)
 
  
  GM_setValue('dynLevelCoef_BTCUSD', [1.74, 2.1])
  GM_setValue('dynLevelCoef_ETHUSD', [2.1, 2.4])
  GM_setValue('dynLevelCoef_XRPUSD', 1.89)
  GM_setValue('dynLevelCoef_ETCUSD', 1.89)
  GM_setValue('dynLevelCoef_ZECUSD', 1.96)
  GM_setValue('dynLevelCoef_DASHUSD', 1.96)
 
  GM_setValue('dynLevelSafe_BTCUSD', 20)
  GM_setValue('dynLevelSafe_ETHUSD', 60)
  GM_setValue('dynLevelSafe_XRPUSD', 50)
  GM_setValue('dynLevelSafe_ETCUSD', 50)
  GM_setValue('dynLevelSafe_ZECUSD', 59)
  GM_setValue('dynLevelSafe_DASHUSD', 54)

GM_setValue('orderSqueezeLimitCur', 0.01)

GM_setValue('percentThreshold_AUDCAD', 80)
GM_setValue('percentThreshold_EURNZD', 99)
GM_setValue('percentThreshold_EURAUD', 99)
GM_setValue('percentThreshold_CHFJPY', 80)
GM_setValue('percentThreshold_USDCHF', 80)
GM_setValue('percentThreshold_EURUSD', 80)
GM_setValue('percentThreshold_GBPUSD', 80)
GM_setValue('percentThreshold_AUDCHF', 99)
GM_setValue('percentThreshold_USDCAD', 80)
GM_setValue('percentThreshold_NZDCAD', 99)

GM_setValue('devThresh_AUDCAD', [-0.010, 0.010])//[LONG, SHORT]
GM_setValue('devThresh_EURNZD', [-0.012, 0.011])
GM_setValue('devThresh_EURAUD', [-0.009, 0.009])
GM_setValue('devThresh_CHFJPY', [-0.008, 0.008])
GM_setValue('devThresh_USDCHF', [-0.008, 0.008])
GM_setValue('devThresh_EURUSD', [-0.006, 0.006])
GM_setValue('devThresh_GBPUSD', [-0.010, 0.0011])
GM_setValue('devThresh_AUDCHF', [-0.009, 0.009])
GM_setValue('devThresh_USDCAD', [-0.008, 0.008])
GM_setValue('devThresh_NZDCAD', [-0.012, 0.011])

  GM_setValue('diffSafe_BTCUSD', [-100, 100])
  GM_setValue('diffSafe_ETHUSD', [-100, 100])
  GM_setValue('diffSafe_XRPUSD', [-100, 100])
  GM_setValue('diffSafe_ETCUSD', [-100, 100])
  GM_setValue('diffSafe_ZECUSD', [-100, 100])
  GM_setValue('diffSafe_DASHUSD', [-100, 100])

GM_setValue('maxBalance', 410)
GM_setValue('minBalance', 30)
GM_setValue('stopLossPercent', 10)
GM_setValue('maxOpenTrades', 1)
GM_setValue('orderSqueezeLimit', 0.07)
GM_setValue('minDelayBetweenOrdersSec', [162, 1280])
GM_setValue('orderUpdate', true)
GM_setValue('reloadOnConnectionReset', true)
GM_setValue('orderUpdateRandomFlag', false)
GM_setValue('orderPercent', 0)
GM_setValue('orderPercentMin', 5)
GM_setValue('orderPercentMax', 5)
GM_setValue('minDelayBetweenOrdersSecDelay', [7200, 10800 ])
GM_setValue('delayLevelToMinOrder', 1.4)
GM_setValue('delayLevelToStop', 2.5)
GM_setValue('orderMinDelay', 1)
GM_setValue('orderMax', 5)
GM_setValue('orderMin', 1)
GM_setValue('orderRoundCoef', 1)
GM_setValue('soundON', false)
