GM_setValue('percentThreshold_BTCUSD', 80)
  GM_setValue('percentThreshold_ETHUSD', 80)
  GM_setValue('percentThreshold_EURUSD', 80)
  GM_setValue('percentThreshold_GBPUSD', 90)

  GM_setValue('diffPercentThreshold_BTCUSD', [-0.08, 0.08])
  GM_setValue('diffPercentThreshold_ETHUSD', [-0.1, 0.1])
  GM_setValue('diffPercentThreshold_EURUSD', [-0.006, 0.006])
  GM_setValue('diffPercentThreshold_GBPUSD', [-0.006, 0.006])

  GM_setValue('diffAgeThreshold_BTCUSD', [0, 15])
  GM_setValue('diffAgeThreshold_ETHUSD', [0, 15])
  GM_setValue('diffAgeThreshold_EURUSD', [0, 15])
  GM_setValue('diffAgeThreshold_GBPUSD', [0, 15])

  GM_setValue('maxBalance', 2000)
  GM_setValue('minBalance', 0)
  GM_setValue('stopLossPercent', 12)
  GM_setValue('orderSqueezeLimit', 0.1)
  GM_setValue('maxOpenTrades', 1)
  GM_setValue('minDelayBetweenOrdersSec', [65, 125])
  GM_setValue('minDelayBetweenOrdersSecDelay', [3600, 7200])
  GM_setValue('delayLevelToMinOrder', 2)
  GM_setValue('delayLevelToStop', 4)
  GM_setValue('orderUpdate', true)
  GM_setValue('orderPercent', 1)
  GM_setValue('orderMax', 200)
  GM_setValue('orderMin', 1)
  GM_setValue('orderRoundCoef', 1)
  GM_setValue('soundON', true)
  GM_setValue('helperKey', '5PmC7fJ4ykaYqEb9yFjYV_v3')
}
